language: php
php:
  - '8.0'
  - '8.1'
  - '8.2'
before_install:
    - composer self-update
    - composer --version
    - composer validate
    - composer install
script:
    - php ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
