language: php
php:
  - '5.6'
  - '7.2'
  - '7.3'
  - '7.4'
before_install:
    - composer self-update
    - composer --version
    - composer validate
    - composer install
script:
    - php ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
