<?php

return [
	[
		'iso'    => 'US-AL',
		'usps'   => 'AL',
		'name'   => 'Alabama',
		'ap'     => 'Ala.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-AK',
		'usps'   => 'AK',
		'name'   => 'Alaska',
		'ap'     => 'Alaska',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-AZ',
		'usps'   => 'AZ',
		'name'   => 'Arizona',
		'ap'     => 'Ariz.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-AR',
		'usps'   => 'AR',
		'name'   => 'Arkansas',
		'ap'     => 'Ark.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-CA',
		'usps'   => 'CA',
		'name'   => 'California',
		'ap'     => 'Calif.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-CO',
		'usps'   => 'CO',
		'name'   => 'Colorado',
		'ap'     => 'Colo.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-CT',
		'usps'   => 'CT',
		'name'   => 'Connecticut',
		'ap'     => 'Conn.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-DE',
		'usps'   => 'DE',
		'name'   => 'Delaware',
		'ap'     => 'Del.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-FL',
		'usps'   => 'FL',
		'name'   => 'Florida',
		'ap'     => 'Fla.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-GA',
		'usps'   => 'GA',
		'name'   => 'Georgia',
		'ap'     => 'Ga.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-HI',
		'usps'   => 'HI',
		'name'   => 'Hawaii',
		'ap'     => 'Hawaii',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-ID',
		'usps'   => 'ID',
		'name'   => 'Idaho',
		'ap'     => 'Idaho',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-IL',
		'usps'   => 'IL',
		'name'   => 'Illinois',
		'ap'     => 'Ill.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-IN',
		'usps'   => 'IN',
		'name'   => 'Indiana',
		'ap'     => 'Ind.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-IA',
		'usps'   => 'IA',
		'name'   => 'Iowa',
		'ap'     => 'Iowa',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-KS',
		'usps'   => 'KS',
		'name'   => 'Kansas',
		'ap'     => 'Kans.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-KY',
		'usps'   => 'KY',
		'name'   => 'Kentucky',
		'ap'     => 'Ky.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-LA',
		'usps'   => 'LA',
		'name'   => 'Louisiana',
		'ap'     => 'La.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-ME',
		'usps'   => 'ME',
		'name'   => 'Maine',
		'ap'     => 'Maine',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MD',
		'usps'   => 'MD',
		'name'   => 'Maryland',
		'ap'     => 'Md.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MA',
		'usps'   => 'MA',
		'name'   => 'Massachusetts',
		'ap'     => 'Mass.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MI',
		'usps'   => 'MI',
		'name'   => 'Michigan',
		'ap'     => 'Mich.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MN',
		'usps'   => 'MN',
		'name'   => 'Minnesota',
		'ap'     => 'Minn.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MS',
		'usps'   => 'MS',
		'name'   => 'Mississippi',
		'ap'     => 'Miss.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MO',
		'usps'   => 'MO',
		'name'   => 'Missouri',
		'ap'     => 'Mo.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-MT',
		'usps'   => 'MT',
		'name'   => 'Montana',
		'ap'     => 'Mont.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NE',
		'usps'   => 'NE',
		'name'   => 'Nebraska',
		'ap'     => 'Nebr.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NV',
		'usps'   => 'NV',
		'name'   => 'Nevada',
		'ap'     => 'Nev.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NH',
		'usps'   => 'NH',
		'name'   => 'New Hampshire',
		'ap'     => 'N.H.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NJ',
		'usps'   => 'NJ',
		'name'   => 'New Jersey',
		'ap'     => 'N.J.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NM',
		'usps'   => 'NM',
		'name'   => 'New Mexico',
		'ap'     => 'N. Mex.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NY',
		'usps'   => 'NY',
		'name'   => 'New York',
		'ap'     => 'N.Y.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-NC',
		'usps'   => 'NC',
		'name'   => 'North Carolina',
		'ap'     => 'N.C.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-ND',
		'usps'   => 'ND',
		'name'   => 'North Dakota',
		'ap'     => 'N. Dak.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-OH',
		'usps'   => 'OH',
		'name'   => 'Ohio',
		'ap'     => 'Ohio',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-OK',
		'usps'   => 'OK',
		'name'   => 'Oklahoma',
		'ap'     => 'Okla.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-OR',
		'usps'   => 'OR',
		'name'   => 'Oregon',
		'ap'     => 'Oreg.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-PA',
		'usps'   => 'PA',
		'name'   => 'Pennsylvania',
		'ap'     => 'Pa.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-RI',
		'usps'   => 'RI',
		'name'   => 'Rhode Island',
		'ap'     => 'R.I.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-SC',
		'usps'   => 'SC',
		'name'   => 'South Carolina',
		'ap'     => 'S.C.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-SD',
		'usps'   => 'SD',
		'name'   => 'South Dakota',
		'ap'     => 'S. Dak.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-TN',
		'usps'   => 'TN',
		'name'   => 'Tennessee',
		'ap'     => 'Tenn.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-TX',
		'usps'   => 'TX',
		'name'   => 'Texas',
		'ap'     => 'Tex.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-UT',
		'usps'   => 'UT',
		'name'   => 'Utah',
		'ap'     => 'Utah',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-VT',
		'usps'   => 'VT',
		'name'   => 'Vermont',
		'ap'     => 'Vt.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-VA',
		'usps'   => 'VA',
		'name'   => 'Virginia',
		'ap'     => 'Va.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-WA',
		'usps'   => 'WA',
		'name'   => 'Washington',
		'ap'     => 'Wash.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-WV',
		'usps'   => 'WV',
		'name'   => 'West Virginia',
		'ap'     => 'W. Va.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-WI',
		'usps'   => 'WI',
		'name'   => 'Wisconsin',
		'ap'     => 'Wis.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-WY',
		'usps'   => 'WY',
		'name'   => 'Wyoming',
		'ap'     => 'Wyo.',
		'parent' => 'US',
		'type'   => 'state',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-DC',
		'usps'   => 'DC',
		'name'   => 'District of Columbia',
		'ap'     => 'D.C.',
		'parent' => 'US',
		'type'   => 'district',
		'CONUS'  => true,
	],
	[
		'iso'    => 'US-AS',
		'usps'   => 'AS',
		'name'   => 'American Samoa',
		'ap'     => 'A.S.',
		'parent' => 'AS',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-GU',
		'usps'   => 'GU',
		'name'   => 'Guam',
		'ap'     => 'Guam',
		'parent' => 'GU',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-MP',
		'usps'   => 'MP',
		'name'   => 'Northern Mariana Islands',
		'ap'     => 'M.P.',
		'parent' => 'MP',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-PR',
		'usps'   => 'PR',
		'name'   => 'Puerto Rico',
		'ap'     => 'P.R.',
		'parent' => 'PR',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-UM',
		'usps'   => 'UM',
		'name'   => 'U.S. Minor Outlying Islands',
		'ap'     => '',
		'parent' => 'UM',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'US-VI',
		'usps'   => 'VI',
		'name'   => 'Virgin Islands, U.S.',
		'ap'     => 'V.I.',
		'parent' => 'VI',
		'type'   => 'outlying territory',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-81',
		'usps'   => '',
		'name'   => 'Baker Island',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'island',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-84',
		'usps'   => '',
		'name'   => 'Howland Island',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'island',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-86',
		'usps'   => '',
		'name'   => 'Jarvis Island',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'island',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-67',
		'usps'   => '',
		'name'   => 'Johnston Atoll',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'atoll',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-89',
		'usps'   => '',
		'name'   => 'Kingman Reef',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'atoll',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-71',
		'usps'   => '',
		'name'   => 'Midway Islands',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'atoll',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-76',
		'usps'   => '',
		'name'   => 'Navassa Island',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'island',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-95',
		'usps'   => '',
		'name'   => 'Palmyra Atoll',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'atoll',
		'CONUS'  => false,
	],
	[
		'iso'    => 'UM-79',
		'usps'   => '',
		'name'   => 'Wake Island',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'atoll',
		'CONUS'  => false,
	],
	[
		'iso'    => 'FM-583',
		'usps'   => 'FM',
		'name'   => 'Micronesia',
		'ap'     => '',
		'parent' => 'FM',
		'type'   => 'freely associated state',
		'CONUS'  => false,
	],
	[
		'iso'    => 'MH-584',
		'usps'   => 'MH',
		'name'   => 'Marshall Islands',
		'ap'     => '',
		'parent' => 'MH',
		'type'   => 'freely associated state',
		'CONUS'  => false,
	],
	[
		'iso'    => 'PW-585',
		'usps'   => 'PW',
		'name'   => 'Palau',
		'ap'     => '',
		'parent' => 'PW',
		'type'   => 'freely associated state',
		'CONUS'  => false,
	],
	[
		'iso'    => '',
		'usps'   => 'AA',
		'name'   => 'Armed Forces Americas',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'us armed forces',
		'CONUS'  => false,
	],
	[
		'iso'    => '',
		'usps'   => 'AE',
		'name'   => 'Armed Forces Europe',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'us armed forces',
		'CONUS'  => false,
	],
	[
		'iso'    => '',
		'usps'   => 'AP',
		'name'   => 'Armed Forces Pacific',
		'ap'     => '',
		'parent' => 'US',
		'type'   => 'us armed forces',
		'CONUS'  => false,
	],

];