<?php

return [
	'aa'                              => 'US',
	'af'                              => 'US',
	'antigua'                         => 'AG',
	'brunei darussalam'               => 'BN',
	'canary islands'                  => 'ES',
	'cape verde islands'              => 'CV',
	'congo democratic republic'       => 'CG',
	'england'                         => 'GB',
	'france metropolitan'             => 'FR',
	'korea republic of'               => 'KR',
	'korea south'                     => 'KR',
	'lao peoples democratic republic' => 'LA',
	'malvinas'                        => 'FK',
	'nevis'                           => 'KN',
	'northern ireland'                => 'GB',
	'russian federation'              => 'RU',
	'saint kitts'                     => 'KN',
	'slovak republic'                 => 'SK',
	'st kitts'                        => 'KN',
	'syrian arab republic'            => 'SY',
	'taiwan province of china'        => 'TW',
	'taiwan republic of china'        => 'TW',
	'tanzania united republic of'     => 'TZ',
	'united kingdom'                  => 'GB',
	'united states of america'        => 'US',
	'vatican'                         => 'VA',
	'virgin islands british'          => 'VG',
	'virgin islands us'               => 'VI',
	'wales'                           => 'GB',
	'western australia'               => 'AU',
];