<?php

return [
	'aa'                                 => 'US',
	'af'                                 => 'US',
	'antigua'                            => 'AG',
	'brunei darussalam'                  => 'BN',
	'canary islands'                     => 'ES',
	'cape verde islands'                 => 'CV',
	'congo'                              => 'CG',
	'congo democratic republic'          => 'CG',
	'cote divoire'                       => 'CI',
	'england'                            => 'GB',
	'france metropolitan'                => 'FR',
	'georgia republic of'                => 'GE',
	'great britain and northern ireland' => 'GB',
	'korea republic of'                  => 'KR',
	'korea south'                        => 'KR',
	'lao peoples democratic republic'    => 'LA',
	'malvinas'                           => 'FK',
	'nevis'                              => 'KN',
	'northern ireland'                   => 'GB',
	'russian federation'                 => 'RU',
	'saint kitts'                        => 'KN',
	'serbia republic of'                 => 'RS',
	'slovak republic slovakia'           => 'SK',
	'slovak republic'                    => 'SK',
	'st kitts'                           => 'KN',
	'syrian arab republic syria'         => 'SY',
	'syrian arab republic'               => 'SY',
	'taiwan province of china'           => 'TW',
	'taiwan republic of china'           => 'TW',
	'tanzania united republic of'        => 'TZ',
	'timor leste'                        => 'TL',
	'timorleste'                         => 'TL',
	'tristan da cunha'                   => 'SH',
	'united kingdom'                     => 'GB',
	'united states of america'           => 'US',
	'united states virgin islands'       => 'VI',
	'vatican'                            => 'VA',
	'virgin islands british'             => 'VG',
	'virgin islands us'                  => 'VI',
	'wales'                              => 'GB',
	'western australia'                  => 'AU',
];