<?php

return [
	[
		'name'    => 'Andorra',
		'iso2'    => 'AD',
		'iso3'    => 'AND',
		'isoNum'  => '020',
		'fips'    => 'AN',
		'capital' => 'Andorra la Vella',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'United Arab Emirates',
		'iso2'    => 'AE',
		'iso3'    => 'ARE',
		'isoNum'  => '784',
		'fips'    => 'AE',
		'capital' => 'Abu Dhabi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Afghanistan',
		'iso2'    => 'AF',
		'iso3'    => 'AFG',
		'isoNum'  => '004',
		'fips'    => 'AF',
		'capital' => 'Kabul',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Antigua and Barbuda',
		'iso2'    => 'AG',
		'iso3'    => 'ATG',
		'isoNum'  => '028',
		'fips'    => 'AC',
		'capital' => 'St. Johns',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Anguilla',
		'iso2'    => 'AI',
		'iso3'    => 'AIA',
		'isoNum'  => '660',
		'fips'    => 'AV',
		'capital' => 'The Valley',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Albania',
		'iso2'    => 'AL',
		'iso3'    => 'ALB',
		'isoNum'  => '008',
		'fips'    => 'AL',
		'capital' => 'Tirana',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Armenia',
		'iso2'    => 'AM',
		'iso3'    => 'ARM',
		'isoNum'  => '051',
		'fips'    => 'AM',
		'capital' => 'Yerevan',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Angola',
		'iso2'    => 'AO',
		'iso3'    => 'AGO',
		'isoNum'  => '024',
		'fips'    => 'AO',
		'capital' => 'Luanda',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Antarctica',
		'iso2'    => 'AQ',
		'iso3'    => 'ATA',
		'isoNum'  => '010',
		'fips'    => 'AY',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Argentina',
		'iso2'    => 'AR',
		'iso3'    => 'ARG',
		'isoNum'  => '032',
		'fips'    => 'AR',
		'capital' => 'Buenos Aires',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'American Samoa',
		'iso2'    => 'AS',
		'iso3'    => 'ASM',
		'isoNum'  => '016',
		'fips'    => 'AQ',
		'capital' => 'Pago Pago',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Austria',
		'iso2'    => 'AT',
		'iso3'    => 'AUT',
		'isoNum'  => '040',
		'fips'    => 'AU',
		'capital' => 'Vienna',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Australia',
		'iso2'    => 'AU',
		'iso3'    => 'AUS',
		'isoNum'  => '036',
		'fips'    => 'AS',
		'capital' => 'Canberra',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Aruba',
		'iso2'    => 'AW',
		'iso3'    => 'ABW',
		'isoNum'  => '533',
		'fips'    => 'AA',
		'capital' => 'Oranjestad',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Åland',
		'iso2'    => 'AX',
		'iso3'    => 'ALA',
		'isoNum'  => '248',
		'fips'    => null,
		'capital' => 'Mariehamn',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Azerbaijan',
		'iso2'    => 'AZ',
		'iso3'    => 'AZE',
		'isoNum'  => '031',
		'fips'    => 'AJ',
		'capital' => 'Baku',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bosnia and Herzegovina',
		'iso2'    => 'BA',
		'iso3'    => 'BIH',
		'isoNum'  => '070',
		'fips'    => 'BK',
		'capital' => 'Sarajevo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Barbados',
		'iso2'    => 'BB',
		'iso3'    => 'BRB',
		'isoNum'  => '052',
		'fips'    => 'BB',
		'capital' => 'Bridgetown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bangladesh',
		'iso2'    => 'BD',
		'iso3'    => 'BGD',
		'isoNum'  => '050',
		'fips'    => 'BG',
		'capital' => 'Dhaka',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Belgium',
		'iso2'    => 'BE',
		'iso3'    => 'BEL',
		'isoNum'  => '056',
		'fips'    => 'BE',
		'capital' => 'Brussels',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Burkina Faso',
		'iso2'    => 'BF',
		'iso3'    => 'BFA',
		'isoNum'  => '854',
		'fips'    => 'UV',
		'capital' => 'Ouagadougou',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bulgaria',
		'iso2'    => 'BG',
		'iso3'    => 'BGR',
		'isoNum'  => '100',
		'fips'    => 'BU',
		'capital' => 'Sofia',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bahrain',
		'iso2'    => 'BH',
		'iso3'    => 'BHR',
		'isoNum'  => '048',
		'fips'    => 'BA',
		'capital' => 'Manama',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Burundi',
		'iso2'    => 'BI',
		'iso3'    => 'BDI',
		'isoNum'  => '108',
		'fips'    => 'BY',
		'capital' => 'Bujumbura',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Benin',
		'iso2'    => 'BJ',
		'iso3'    => 'BEN',
		'isoNum'  => '204',
		'fips'    => 'BN',
		'capital' => 'Porto-Novo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Barthélemy',
		'iso2'    => 'BL',
		'iso3'    => 'BLM',
		'isoNum'  => '652',
		'fips'    => 'TB',
		'capital' => 'Gustavia',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bermuda',
		'iso2'    => 'BM',
		'iso3'    => 'BMU',
		'isoNum'  => '060',
		'fips'    => 'BD',
		'capital' => 'Hamilton',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Brunei',
		'iso2'    => 'BN',
		'iso3'    => 'BRN',
		'isoNum'  => '096',
		'fips'    => 'BX',
		'capital' => 'Bandar Seri Begawan',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bolivia',
		'iso2'    => 'BO',
		'iso3'    => 'BOL',
		'isoNum'  => '068',
		'fips'    => 'BL',
		'capital' => 'Sucre',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bonaire',
		'iso2'    => 'BQ',
		'iso3'    => 'BES',
		'isoNum'  => '535',
		'fips'    => '',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Brazil',
		'iso2'    => 'BR',
		'iso3'    => 'BRA',
		'isoNum'  => '076',
		'fips'    => 'BR',
		'capital' => 'Brasília',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bahamas',
		'iso2'    => 'BS',
		'iso3'    => 'BHS',
		'isoNum'  => '044',
		'fips'    => 'BF',
		'capital' => 'Nassau',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bhutan',
		'iso2'    => 'BT',
		'iso3'    => 'BTN',
		'isoNum'  => '064',
		'fips'    => 'BT',
		'capital' => 'Thimphu',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Bouvet Island',
		'iso2'    => 'BV',
		'iso3'    => 'BVT',
		'isoNum'  => '074',
		'fips'    => 'BV',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Botswana',
		'iso2'    => 'BW',
		'iso3'    => 'BWA',
		'isoNum'  => '072',
		'fips'    => 'BC',
		'capital' => 'Gaborone',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Belarus',
		'iso2'    => 'BY',
		'iso3'    => 'BLR',
		'isoNum'  => '112',
		'fips'    => 'BO',
		'capital' => 'Minsk',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Belize',
		'iso2'    => 'BZ',
		'iso3'    => 'BLZ',
		'isoNum'  => '084',
		'fips'    => 'BH',
		'capital' => 'Belmopan',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Canada',
		'iso2'    => 'CA',
		'iso3'    => 'CAN',
		'isoNum'  => '124',
		'fips'    => 'CA',
		'capital' => 'Ottawa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cocos [Keeling] Islands',
		'iso2'    => 'CC',
		'iso3'    => 'CCK',
		'isoNum'  => '166',
		'fips'    => 'CK',
		'capital' => 'West Island',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Democratic Republic of the Con',
		'iso2'    => 'CD',
		'iso3'    => 'COD',
		'isoNum'  => '180',
		'fips'    => 'CG',
		'capital' => 'Kinshasa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Central African Republic',
		'iso2'    => 'CF',
		'iso3'    => 'CAF',
		'isoNum'  => '140',
		'fips'    => 'CT',
		'capital' => 'Bangui',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Republic of the Congo',
		'iso2'    => 'CG',
		'iso3'    => 'COG',
		'isoNum'  => '178',
		'fips'    => 'CF',
		'capital' => 'Brazzaville',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Switzerland',
		'iso2'    => 'CH',
		'iso3'    => 'CHE',
		'isoNum'  => '756',
		'fips'    => 'SZ',
		'capital' => 'Berne',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ivory Coast',
		'iso2'    => 'CI',
		'iso3'    => 'CIV',
		'isoNum'  => '384',
		'fips'    => 'IV',
		'capital' => 'Yamoussoukro',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cook Islands',
		'iso2'    => 'CK',
		'iso3'    => 'COK',
		'isoNum'  => '184',
		'fips'    => 'CW',
		'capital' => 'Avarua',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Chile',
		'iso2'    => 'CL',
		'iso3'    => 'CHL',
		'isoNum'  => '152',
		'fips'    => 'CI',
		'capital' => 'Santiago',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cameroon',
		'iso2'    => 'CM',
		'iso3'    => 'CMR',
		'isoNum'  => '120',
		'fips'    => 'CM',
		'capital' => 'Yaoundé',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'China',
		'iso2'    => 'CN',
		'iso3'    => 'CHN',
		'isoNum'  => '156',
		'fips'    => 'CH',
		'capital' => 'Beijing',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Colombia',
		'iso2'    => 'CO',
		'iso3'    => 'COL',
		'isoNum'  => '170',
		'fips'    => 'CO',
		'capital' => 'Bogotá',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Costa Rica',
		'iso2'    => 'CR',
		'iso3'    => 'CRI',
		'isoNum'  => '188',
		'fips'    => 'CS',
		'capital' => 'San José',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cuba',
		'iso2'    => 'CU',
		'iso3'    => 'CUB',
		'isoNum'  => '192',
		'fips'    => 'CU',
		'capital' => 'Havana',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cape Verde',
		'iso2'    => 'CV',
		'iso3'    => 'CPV',
		'isoNum'  => '132',
		'fips'    => 'CV',
		'capital' => 'Praia',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Curacao',
		'iso2'    => 'CW',
		'iso3'    => 'CUW',
		'isoNum'  => '531',
		'fips'    => 'UC',
		'capital' => 'Willemstad',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Christmas Island',
		'iso2'    => 'CX',
		'iso3'    => 'CXR',
		'isoNum'  => '162',
		'fips'    => 'KT',
		'capital' => 'The Settlement',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cyprus',
		'iso2'    => 'CY',
		'iso3'    => 'CYP',
		'isoNum'  => '196',
		'fips'    => 'CY',
		'capital' => 'Nicosia',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Czech Republic',
		'iso2'    => 'CZ',
		'iso3'    => 'CZE',
		'isoNum'  => '203',
		'fips'    => 'EZ',
		'capital' => 'Prague',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Germany',
		'iso2'    => 'DE',
		'iso3'    => 'DEU',
		'isoNum'  => '276',
		'fips'    => 'GM',
		'capital' => 'Berlin',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Djibouti',
		'iso2'    => 'DJ',
		'iso3'    => 'DJI',
		'isoNum'  => '262',
		'fips'    => 'DJ',
		'capital' => 'Djibouti',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Denmark',
		'iso2'    => 'DK',
		'iso3'    => 'DNK',
		'isoNum'  => '208',
		'fips'    => 'DA',
		'capital' => 'Copenhagen',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Dominica',
		'iso2'    => 'DM',
		'iso3'    => 'DMA',
		'isoNum'  => '212',
		'fips'    => 'DO',
		'capital' => 'Roseau',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Dominican Republic',
		'iso2'    => 'DO',
		'iso3'    => 'DOM',
		'isoNum'  => '214',
		'fips'    => 'DR',
		'capital' => 'Santo Domingo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Algeria',
		'iso2'    => 'DZ',
		'iso3'    => 'DZA',
		'isoNum'  => '012',
		'fips'    => 'AG',
		'capital' => 'Algiers',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ecuador',
		'iso2'    => 'EC',
		'iso3'    => 'ECU',
		'isoNum'  => '218',
		'fips'    => 'EC',
		'capital' => 'Quito',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Estonia',
		'iso2'    => 'EE',
		'iso3'    => 'EST',
		'isoNum'  => '233',
		'fips'    => 'EN',
		'capital' => 'Tallinn',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Egypt',
		'iso2'    => 'EG',
		'iso3'    => 'EGY',
		'isoNum'  => '818',
		'fips'    => 'EG',
		'capital' => 'Cairo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Western Sahara',
		'iso2'    => 'EH',
		'iso3'    => 'ESH',
		'isoNum'  => '732',
		'fips'    => 'WI',
		'capital' => 'El Aaiún',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Eritrea',
		'iso2'    => 'ER',
		'iso3'    => 'ERI',
		'isoNum'  => '232',
		'fips'    => 'ER',
		'capital' => 'Asmara',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Spain',
		'iso2'    => 'ES',
		'iso3'    => 'ESP',
		'isoNum'  => '724',
		'fips'    => 'SP',
		'capital' => 'Madrid',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ethiopia',
		'iso2'    => 'ET',
		'iso3'    => 'ETH',
		'isoNum'  => '231',
		'fips'    => 'ET',
		'capital' => 'Addis Ababa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Finland',
		'iso2'    => 'FI',
		'iso3'    => 'FIN',
		'isoNum'  => '246',
		'fips'    => 'FI',
		'capital' => 'Helsinki',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Fiji',
		'iso2'    => 'FJ',
		'iso3'    => 'FJI',
		'isoNum'  => '242',
		'fips'    => 'FJ',
		'capital' => 'Suva',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Falkland Islands',
		'iso2'    => 'FK',
		'iso3'    => 'FLK',
		'isoNum'  => '238',
		'fips'    => 'FK',
		'capital' => 'Stanley',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Micronesia',
		'iso2'    => 'FM',
		'iso3'    => 'FSM',
		'isoNum'  => '583',
		'fips'    => 'FM',
		'capital' => 'Palikir',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Faroe Islands',
		'iso2'    => 'FO',
		'iso3'    => 'FRO',
		'isoNum'  => '234',
		'fips'    => 'FO',
		'capital' => 'Tórshavn',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'France',
		'iso2'    => 'FR',
		'iso3'    => 'FRA',
		'isoNum'  => '250',
		'fips'    => 'FR',
		'capital' => 'Paris',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Gabon',
		'iso2'    => 'GA',
		'iso3'    => 'GAB',
		'isoNum'  => '266',
		'fips'    => 'GB',
		'capital' => 'Libreville',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'United Kingdom',
		'iso2'    => 'GB',
		'iso3'    => 'GBR',
		'isoNum'  => '826',
		'fips'    => 'UK',
		'capital' => 'London',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Grenada',
		'iso2'    => 'GD',
		'iso3'    => 'GRD',
		'isoNum'  => '308',
		'fips'    => 'GJ',
		'capital' => 'St. Georges',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Georgia',
		'iso2'    => 'GE',
		'iso3'    => 'GEO',
		'isoNum'  => '268',
		'fips'    => 'GG',
		'capital' => 'Tbilisi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'French Guiana',
		'iso2'    => 'GF',
		'iso3'    => 'GUF',
		'isoNum'  => '254',
		'fips'    => 'FG',
		'capital' => 'Cayenne',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guernsey',
		'iso2'    => 'GG',
		'iso3'    => 'GGY',
		'isoNum'  => '831',
		'fips'    => 'GK',
		'capital' => 'St Peter Port',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ghana',
		'iso2'    => 'GH',
		'iso3'    => 'GHA',
		'isoNum'  => '288',
		'fips'    => 'GH',
		'capital' => 'Accra',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Gibraltar',
		'iso2'    => 'GI',
		'iso3'    => 'GIB',
		'isoNum'  => '292',
		'fips'    => 'GI',
		'capital' => 'Gibraltar',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Greenland',
		'iso2'    => 'GL',
		'iso3'    => 'GRL',
		'isoNum'  => '304',
		'fips'    => 'GL',
		'capital' => 'Nuuk',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Gambia',
		'iso2'    => 'GM',
		'iso3'    => 'GMB',
		'isoNum'  => '270',
		'fips'    => 'GA',
		'capital' => 'Banjul',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guinea',
		'iso2'    => 'GN',
		'iso3'    => 'GIN',
		'isoNum'  => '324',
		'fips'    => 'GV',
		'capital' => 'Conakry',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guadeloupe',
		'iso2'    => 'GP',
		'iso3'    => 'GLP',
		'isoNum'  => '312',
		'fips'    => 'GP',
		'capital' => 'Basse-Terre',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Equatorial Guinea',
		'iso2'    => 'GQ',
		'iso3'    => 'GNQ',
		'isoNum'  => '226',
		'fips'    => 'EK',
		'capital' => 'Malabo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Greece',
		'iso2'    => 'GR',
		'iso3'    => 'GRC',
		'isoNum'  => '300',
		'fips'    => 'GR',
		'capital' => 'Athens',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'South Georgia and the South Sa',
		'iso2'    => 'GS',
		'iso3'    => 'SGS',
		'isoNum'  => '239',
		'fips'    => 'SX',
		'capital' => 'Grytviken',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guatemala',
		'iso2'    => 'GT',
		'iso3'    => 'GTM',
		'isoNum'  => '320',
		'fips'    => 'GT',
		'capital' => 'Guatemala City',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guam',
		'iso2'    => 'GU',
		'iso3'    => 'GUM',
		'isoNum'  => '316',
		'fips'    => 'GQ',
		'capital' => 'Hagåtña',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Guinea-Bissau',
		'iso2'    => 'GW',
		'iso3'    => 'GNB',
		'isoNum'  => '624',
		'fips'    => 'PU',
		'capital' => 'Bissau',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Guyana',
		'iso2'    => 'GY',
		'iso3'    => 'GUY',
		'isoNum'  => '328',
		'fips'    => 'GY',
		'capital' => 'Georgetown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Hong Kong',
		'iso2'    => 'HK',
		'iso3'    => 'HKG',
		'isoNum'  => '344',
		'fips'    => 'HK',
		'capital' => 'Hong Kong',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Heard Island and McDonald Isla',
		'iso2'    => 'HM',
		'iso3'    => 'HMD',
		'isoNum'  => '334',
		'fips'    => 'HM',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Honduras',
		'iso2'    => 'HN',
		'iso3'    => 'HND',
		'isoNum'  => '340',
		'fips'    => 'HO',
		'capital' => 'Tegucigalpa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Croatia',
		'iso2'    => 'HR',
		'iso3'    => 'HRV',
		'isoNum'  => '191',
		'fips'    => 'HR',
		'capital' => 'Zagreb',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Haiti',
		'iso2'    => 'HT',
		'iso3'    => 'HTI',
		'isoNum'  => '332',
		'fips'    => 'HA',
		'capital' => 'Port-au-Prince',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Hungary',
		'iso2'    => 'HU',
		'iso3'    => 'HUN',
		'isoNum'  => '348',
		'fips'    => 'HU',
		'capital' => 'Budapest',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Indonesia',
		'iso2'    => 'ID',
		'iso3'    => 'IDN',
		'isoNum'  => '360',
		'fips'    => 'ID',
		'capital' => 'Jakarta',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ireland',
		'iso2'    => 'IE',
		'iso3'    => 'IRL',
		'isoNum'  => '372',
		'fips'    => 'EI',
		'capital' => 'Dublin',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Israel',
		'iso2'    => 'IL',
		'iso3'    => 'ISR',
		'isoNum'  => '376',
		'fips'    => 'IS',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Isle of Man',
		'iso2'    => 'IM',
		'iso3'    => 'IMN',
		'isoNum'  => '833',
		'fips'    => 'IM',
		'capital' => 'Douglas',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'India',
		'iso2'    => 'IN',
		'iso3'    => 'IND',
		'isoNum'  => '356',
		'fips'    => 'IN',
		'capital' => 'New Delhi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'British Indian Ocean Territory',
		'iso2'    => 'IO',
		'iso3'    => 'IOT',
		'isoNum'  => '086',
		'fips'    => 'IO',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Iraq',
		'iso2'    => 'IQ',
		'iso3'    => 'IRQ',
		'isoNum'  => '368',
		'fips'    => 'IZ',
		'capital' => 'Baghdad',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Iran',
		'iso2'    => 'IR',
		'iso3'    => 'IRN',
		'isoNum'  => '364',
		'fips'    => 'IR',
		'capital' => 'Tehran',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Iceland',
		'iso2'    => 'IS',
		'iso3'    => 'ISL',
		'isoNum'  => '352',
		'fips'    => 'IC',
		'capital' => 'Reykjavik',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Italy',
		'iso2'    => 'IT',
		'iso3'    => 'ITA',
		'isoNum'  => '380',
		'fips'    => 'IT',
		'capital' => 'Rome',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Jersey',
		'iso2'    => 'JE',
		'iso3'    => 'JEY',
		'isoNum'  => '832',
		'fips'    => 'JE',
		'capital' => 'Saint Helier',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Jamaica',
		'iso2'    => 'JM',
		'iso3'    => 'JAM',
		'isoNum'  => '388',
		'fips'    => 'JM',
		'capital' => 'Kingston',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Jordan',
		'iso2'    => 'JO',
		'iso3'    => 'JOR',
		'isoNum'  => '400',
		'fips'    => 'JO',
		'capital' => 'Amman',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Japan',
		'iso2'    => 'JP',
		'iso3'    => 'JPN',
		'isoNum'  => '392',
		'fips'    => 'JA',
		'capital' => 'Tokyo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kenya',
		'iso2'    => 'KE',
		'iso3'    => 'KEN',
		'isoNum'  => '404',
		'fips'    => 'KE',
		'capital' => 'Nairobi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kyrgyzstan',
		'iso2'    => 'KG',
		'iso3'    => 'KGZ',
		'isoNum'  => '417',
		'fips'    => 'KG',
		'capital' => 'Bishkek',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cambodia',
		'iso2'    => 'KH',
		'iso3'    => 'KHM',
		'isoNum'  => '116',
		'fips'    => 'CB',
		'capital' => 'Phnom Penh',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kiribati',
		'iso2'    => 'KI',
		'iso3'    => 'KIR',
		'isoNum'  => '296',
		'fips'    => 'KR',
		'capital' => 'Tarawa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Comoros',
		'iso2'    => 'KM',
		'iso3'    => 'COM',
		'isoNum'  => '174',
		'fips'    => 'CN',
		'capital' => 'Moroni',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Kitts and Nevis',
		'iso2'    => 'KN',
		'iso3'    => 'KNA',
		'isoNum'  => '659',
		'fips'    => 'SC',
		'capital' => 'Basseterre',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'North Korea',
		'iso2'    => 'KP',
		'iso3'    => 'PRK',
		'isoNum'  => '408',
		'fips'    => 'KN',
		'capital' => 'Pyongyang',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'South Korea',
		'iso2'    => 'KR',
		'iso3'    => 'KOR',
		'isoNum'  => '410',
		'fips'    => 'KS',
		'capital' => 'Seoul',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kuwait',
		'iso2'    => 'KW',
		'iso3'    => 'KWT',
		'isoNum'  => '414',
		'fips'    => 'KU',
		'capital' => 'Kuwait City',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Cayman Islands',
		'iso2'    => 'KY',
		'iso3'    => 'CYM',
		'isoNum'  => '136',
		'fips'    => 'CJ',
		'capital' => 'George Town',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kazakhstan',
		'iso2'    => 'KZ',
		'iso3'    => 'KAZ',
		'isoNum'  => '398',
		'fips'    => 'KZ',
		'capital' => 'Astana',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Laos',
		'iso2'    => 'LA',
		'iso3'    => 'LAO',
		'isoNum'  => '418',
		'fips'    => 'LA',
		'capital' => 'Vientiane',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Lebanon',
		'iso2'    => 'LB',
		'iso3'    => 'LBN',
		'isoNum'  => '422',
		'fips'    => 'LE',
		'capital' => 'Beirut',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Lucia',
		'iso2'    => 'LC',
		'iso3'    => 'LCA',
		'isoNum'  => '662',
		'fips'    => 'ST',
		'capital' => 'Castries',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Liechtenstein',
		'iso2'    => 'LI',
		'iso3'    => 'LIE',
		'isoNum'  => '438',
		'fips'    => 'LS',
		'capital' => 'Vaduz',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Sri Lanka',
		'iso2'    => 'LK',
		'iso3'    => 'LKA',
		'isoNum'  => '144',
		'fips'    => 'CE',
		'capital' => 'Colombo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Liberia',
		'iso2'    => 'LR',
		'iso3'    => 'LBR',
		'isoNum'  => '430',
		'fips'    => 'LI',
		'capital' => 'Monrovia',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Lesotho',
		'iso2'    => 'LS',
		'iso3'    => 'LSO',
		'isoNum'  => '426',
		'fips'    => 'LT',
		'capital' => 'Maseru',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Lithuania',
		'iso2'    => 'LT',
		'iso3'    => 'LTU',
		'isoNum'  => '440',
		'fips'    => 'LH',
		'capital' => 'Vilnius',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Luxembourg',
		'iso2'    => 'LU',
		'iso3'    => 'LUX',
		'isoNum'  => '442',
		'fips'    => 'LU',
		'capital' => 'Luxembourg',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Latvia',
		'iso2'    => 'LV',
		'iso3'    => 'LVA',
		'isoNum'  => '428',
		'fips'    => 'LG',
		'capital' => 'Riga',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Libya',
		'iso2'    => 'LY',
		'iso3'    => 'LBY',
		'isoNum'  => '434',
		'fips'    => 'LY',
		'capital' => 'Tripoli',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Morocco',
		'iso2'    => 'MA',
		'iso3'    => 'MAR',
		'isoNum'  => '504',
		'fips'    => 'MO',
		'capital' => 'Rabat',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Monaco',
		'iso2'    => 'MC',
		'iso3'    => 'MCO',
		'isoNum'  => '492',
		'fips'    => 'MN',
		'capital' => 'Monaco',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Moldova',
		'iso2'    => 'MD',
		'iso3'    => 'MDA',
		'isoNum'  => '498',
		'fips'    => 'MD',
		'capital' => 'Chişinău',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Montenegro',
		'iso2'    => 'ME',
		'iso3'    => 'MNE',
		'isoNum'  => '499',
		'fips'    => 'MJ',
		'capital' => 'Podgorica',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Martin',
		'iso2'    => 'MF',
		'iso3'    => 'MAF',
		'isoNum'  => '663',
		'fips'    => 'RN',
		'capital' => 'Marigot',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Madagascar',
		'iso2'    => 'MG',
		'iso3'    => 'MDG',
		'isoNum'  => '450',
		'fips'    => 'MA',
		'capital' => 'Antananarivo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Marshall Islands',
		'iso2'    => 'MH',
		'iso3'    => 'MHL',
		'isoNum'  => '584',
		'fips'    => 'RM',
		'capital' => 'Majuro',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Macedonia',
		'iso2'    => 'MK',
		'iso3'    => 'MKD',
		'isoNum'  => '807',
		'fips'    => 'MK',
		'capital' => 'Skopje',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mali',
		'iso2'    => 'ML',
		'iso3'    => 'MLI',
		'isoNum'  => '466',
		'fips'    => 'ML',
		'capital' => 'Bamako',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Myanmar [Burma]',
		'iso2'    => 'MM',
		'iso3'    => 'MMR',
		'isoNum'  => '104',
		'fips'    => 'BM',
		'capital' => 'Nay Pyi Taw',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mongolia',
		'iso2'    => 'MN',
		'iso3'    => 'MNG',
		'isoNum'  => '496',
		'fips'    => 'MG',
		'capital' => 'Ulan Bator',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Macao',
		'iso2'    => 'MO',
		'iso3'    => 'MAC',
		'isoNum'  => '446',
		'fips'    => 'MC',
		'capital' => 'Macao',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Northern Mariana Islands',
		'iso2'    => 'MP',
		'iso3'    => 'MNP',
		'isoNum'  => '580',
		'fips'    => 'CQ',
		'capital' => 'Saipan',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Martinique',
		'iso2'    => 'MQ',
		'iso3'    => 'MTQ',
		'isoNum'  => '474',
		'fips'    => 'MB',
		'capital' => 'Fort-de-France',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mauritania',
		'iso2'    => 'MR',
		'iso3'    => 'MRT',
		'isoNum'  => '478',
		'fips'    => 'MR',
		'capital' => 'Nouakchott',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Montserrat',
		'iso2'    => 'MS',
		'iso3'    => 'MSR',
		'isoNum'  => '500',
		'fips'    => 'MH',
		'capital' => 'Plymouth',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Malta',
		'iso2'    => 'MT',
		'iso3'    => 'MLT',
		'isoNum'  => '470',
		'fips'    => 'MT',
		'capital' => 'Valletta',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mauritius',
		'iso2'    => 'MU',
		'iso3'    => 'MUS',
		'isoNum'  => '480',
		'fips'    => 'MP',
		'capital' => 'Port Louis',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Maldives',
		'iso2'    => 'MV',
		'iso3'    => 'MDV',
		'isoNum'  => '462',
		'fips'    => 'MV',
		'capital' => 'Malé',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Malawi',
		'iso2'    => 'MW',
		'iso3'    => 'MWI',
		'isoNum'  => '454',
		'fips'    => 'MI',
		'capital' => 'Lilongwe',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mexico',
		'iso2'    => 'MX',
		'iso3'    => 'MEX',
		'isoNum'  => '484',
		'fips'    => 'MX',
		'capital' => 'Mexico City',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Malaysia',
		'iso2'    => 'MY',
		'iso3'    => 'MYS',
		'isoNum'  => '458',
		'fips'    => 'MY',
		'capital' => 'Kuala Lumpur',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mozambique',
		'iso2'    => 'MZ',
		'iso3'    => 'MOZ',
		'isoNum'  => '508',
		'fips'    => 'MZ',
		'capital' => 'Maputo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Namibia',
		'iso2'    => 'NA',
		'iso3'    => 'NAM',
		'isoNum'  => '516',
		'fips'    => 'WA',
		'capital' => 'Windhoek',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'New Caledonia',
		'iso2'    => 'NC',
		'iso3'    => 'NCL',
		'isoNum'  => '540',
		'fips'    => 'NC',
		'capital' => 'Noumea',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Niger',
		'iso2'    => 'NE',
		'iso3'    => 'NER',
		'isoNum'  => '562',
		'fips'    => 'NG',
		'capital' => 'Niamey',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Norfolk Island',
		'iso2'    => 'NF',
		'iso3'    => 'NFK',
		'isoNum'  => '574',
		'fips'    => 'NF',
		'capital' => 'Kingston',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Nigeria',
		'iso2'    => 'NG',
		'iso3'    => 'NGA',
		'isoNum'  => '566',
		'fips'    => 'NI',
		'capital' => 'Abuja',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Nicaragua',
		'iso2'    => 'NI',
		'iso3'    => 'NIC',
		'isoNum'  => '558',
		'fips'    => 'NU',
		'capital' => 'Managua',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Netherlands',
		'iso2'    => 'NL',
		'iso3'    => 'NLD',
		'isoNum'  => '528',
		'fips'    => 'NL',
		'capital' => 'Amsterdam',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Norway',
		'iso2'    => 'NO',
		'iso3'    => 'NOR',
		'isoNum'  => '578',
		'fips'    => 'NO',
		'capital' => 'Oslo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Nepal',
		'iso2'    => 'NP',
		'iso3'    => 'NPL',
		'isoNum'  => '524',
		'fips'    => 'NP',
		'capital' => 'Kathmandu',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Nauru',
		'iso2'    => 'NR',
		'iso3'    => 'NRU',
		'isoNum'  => '520',
		'fips'    => 'NR',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Niue',
		'iso2'    => 'NU',
		'iso3'    => 'NIU',
		'isoNum'  => '570',
		'fips'    => 'NE',
		'capital' => 'Alofi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'New Zealand',
		'iso2'    => 'NZ',
		'iso3'    => 'NZL',
		'isoNum'  => '554',
		'fips'    => 'NZ',
		'capital' => 'Wellington',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Oman',
		'iso2'    => 'OM',
		'iso3'    => 'OMN',
		'isoNum'  => '512',
		'fips'    => 'MU',
		'capital' => 'Muscat',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Panama',
		'iso2'    => 'PA',
		'iso3'    => 'PAN',
		'isoNum'  => '591',
		'fips'    => 'PM',
		'capital' => 'Panama City',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Peru',
		'iso2'    => 'PE',
		'iso3'    => 'PER',
		'isoNum'  => '604',
		'fips'    => 'PE',
		'capital' => 'Lima',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'French Polynesia',
		'iso2'    => 'PF',
		'iso3'    => 'PYF',
		'isoNum'  => '258',
		'fips'    => 'FP',
		'capital' => 'Papeete',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Papua New Guinea',
		'iso2'    => 'PG',
		'iso3'    => 'PNG',
		'isoNum'  => '598',
		'fips'    => 'PP',
		'capital' => 'Port Moresby',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Philippines',
		'iso2'    => 'PH',
		'iso3'    => 'PHL',
		'isoNum'  => '608',
		'fips'    => 'RP',
		'capital' => 'Manila',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Pakistan',
		'iso2'    => 'PK',
		'iso3'    => 'PAK',
		'isoNum'  => '586',
		'fips'    => 'PK',
		'capital' => 'Islamabad',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Poland',
		'iso2'    => 'PL',
		'iso3'    => 'POL',
		'isoNum'  => '616',
		'fips'    => 'PL',
		'capital' => 'Warsaw',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Pierre and Miquelon',
		'iso2'    => 'PM',
		'iso3'    => 'SPM',
		'isoNum'  => '666',
		'fips'    => 'SB',
		'capital' => 'Saint-Pierre',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Pitcairn Islands',
		'iso2'    => 'PN',
		'iso3'    => 'PCN',
		'isoNum'  => '612',
		'fips'    => 'PC',
		'capital' => 'Adamstown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Puerto Rico',
		'iso2'    => 'PR',
		'iso3'    => 'PRI',
		'isoNum'  => '630',
		'fips'    => 'RQ',
		'capital' => 'San Juan',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Palestine',
		'iso2'    => 'PS',
		'iso3'    => 'PSE',
		'isoNum'  => '275',
		'fips'    => 'WE',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Portugal',
		'iso2'    => 'PT',
		'iso3'    => 'PRT',
		'isoNum'  => '620',
		'fips'    => 'PO',
		'capital' => 'Lisbon',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Palau',
		'iso2'    => 'PW',
		'iso3'    => 'PLW',
		'isoNum'  => '585',
		'fips'    => 'PS',
		'capital' => 'Melekeok - Palau State Capital',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Paraguay',
		'iso2'    => 'PY',
		'iso3'    => 'PRY',
		'isoNum'  => '600',
		'fips'    => 'PA',
		'capital' => 'Asunción',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Qatar',
		'iso2'    => 'QA',
		'iso3'    => 'QAT',
		'isoNum'  => '634',
		'fips'    => 'QA',
		'capital' => 'Doha',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Réunion',
		'iso2'    => 'RE',
		'iso3'    => 'REU',
		'isoNum'  => '638',
		'fips'    => 'RE',
		'capital' => 'Saint-Denis',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Romania',
		'iso2'    => 'RO',
		'iso3'    => 'ROU',
		'isoNum'  => '642',
		'fips'    => 'RO',
		'capital' => 'Bucharest',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Serbia',
		'iso2'    => 'RS',
		'iso3'    => 'SRB',
		'isoNum'  => '688',
		'fips'    => 'RI',
		'capital' => 'Belgrade',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Russia',
		'iso2'    => 'RU',
		'iso3'    => 'RUS',
		'isoNum'  => '643',
		'fips'    => 'RS',
		'capital' => 'Moscow',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Rwanda',
		'iso2'    => 'RW',
		'iso3'    => 'RWA',
		'isoNum'  => '646',
		'fips'    => 'RW',
		'capital' => 'Kigali',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saudi Arabia',
		'iso2'    => 'SA',
		'iso3'    => 'SAU',
		'isoNum'  => '682',
		'fips'    => 'SA',
		'capital' => 'Riyadh',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Solomon Islands',
		'iso2'    => 'SB',
		'iso3'    => 'SLB',
		'isoNum'  => '090',
		'fips'    => 'BP',
		'capital' => 'Honiara',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Seychelles',
		'iso2'    => 'SC',
		'iso3'    => 'SYC',
		'isoNum'  => '690',
		'fips'    => 'SE',
		'capital' => 'Victoria',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Sudan',
		'iso2'    => 'SD',
		'iso3'    => 'SDN',
		'isoNum'  => '729',
		'fips'    => 'SU',
		'capital' => 'Khartoum',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Sweden',
		'iso2'    => 'SE',
		'iso3'    => 'SWE',
		'isoNum'  => '752',
		'fips'    => 'SW',
		'capital' => 'Stockholm',
		'isEU'    => 1,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Singapore',
		'iso2'    => 'SG',
		'iso3'    => 'SGP',
		'isoNum'  => '702',
		'fips'    => 'SN',
		'capital' => 'Singapore',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Helena',
		'iso2'    => 'SH',
		'iso3'    => 'SHN',
		'isoNum'  => '654',
		'fips'    => 'SH',
		'capital' => 'Jamestown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Slovenia',
		'iso2'    => 'SI',
		'iso3'    => 'SVN',
		'isoNum'  => '705',
		'fips'    => 'SI',
		'capital' => 'Ljubljana',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Svalbard and Jan Mayen',
		'iso2'    => 'SJ',
		'iso3'    => 'SJM',
		'isoNum'  => '744',
		'fips'    => 'SV',
		'capital' => 'Longyearbyen',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Slovakia',
		'iso2'    => 'SK',
		'iso3'    => 'SVK',
		'isoNum'  => '703',
		'fips'    => 'LO',
		'capital' => 'Bratislava',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Sierra Leone',
		'iso2'    => 'SL',
		'iso3'    => 'SLE',
		'isoNum'  => '694',
		'fips'    => 'SL',
		'capital' => 'Freetown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'San Marino',
		'iso2'    => 'SM',
		'iso3'    => 'SMR',
		'isoNum'  => '674',
		'fips'    => 'SM',
		'capital' => 'San Marino',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Senegal',
		'iso2'    => 'SN',
		'iso3'    => 'SEN',
		'isoNum'  => '686',
		'fips'    => 'SG',
		'capital' => 'Dakar',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Somalia',
		'iso2'    => 'SO',
		'iso3'    => 'SOM',
		'isoNum'  => '706',
		'fips'    => 'SO',
		'capital' => 'Mogadishu',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Suriname',
		'iso2'    => 'SR',
		'iso3'    => 'SUR',
		'isoNum'  => '740',
		'fips'    => 'NS',
		'capital' => 'Paramaribo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'South Sudan',
		'iso2'    => 'SS',
		'iso3'    => 'SSD',
		'isoNum'  => '728',
		'fips'    => 'OD',
		'capital' => 'Juba',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'São Tomé and Príncipe',
		'iso2'    => 'ST',
		'iso3'    => 'STP',
		'isoNum'  => '678',
		'fips'    => 'TP',
		'capital' => 'São Tomé',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'El Salvador',
		'iso2'    => 'SV',
		'iso3'    => 'SLV',
		'isoNum'  => '222',
		'fips'    => 'ES',
		'capital' => 'San Salvador',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Sint Maarten',
		'iso2'    => 'SX',
		'iso3'    => 'SXM',
		'isoNum'  => '534',
		'fips'    => 'NN',
		'capital' => 'Philipsburg',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Syria',
		'iso2'    => 'SY',
		'iso3'    => 'SYR',
		'isoNum'  => '760',
		'fips'    => 'SY',
		'capital' => 'Damascus',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Swaziland',
		'iso2'    => 'SZ',
		'iso3'    => 'SWZ',
		'isoNum'  => '748',
		'fips'    => 'WZ',
		'capital' => 'Mbabane',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Turks and Caicos Islands',
		'iso2'    => 'TC',
		'iso3'    => 'TCA',
		'isoNum'  => '796',
		'fips'    => 'TK',
		'capital' => 'Cockburn Town',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Chad',
		'iso2'    => 'TD',
		'iso3'    => 'TCD',
		'isoNum'  => '148',
		'fips'    => 'CD',
		'capital' => 'NDjamena',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'French Southern Territories',
		'iso2'    => 'TF',
		'iso3'    => 'ATF',
		'isoNum'  => '260',
		'fips'    => 'FS',
		'capital' => 'Port-aux-Français',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Togo',
		'iso2'    => 'TG',
		'iso3'    => 'TGO',
		'isoNum'  => '768',
		'fips'    => 'TO',
		'capital' => 'Lomé',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Thailand',
		'iso2'    => 'TH',
		'iso3'    => 'THA',
		'isoNum'  => '764',
		'fips'    => 'TH',
		'capital' => 'Bangkok',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tajikistan',
		'iso2'    => 'TJ',
		'iso3'    => 'TJK',
		'isoNum'  => '762',
		'fips'    => 'TI',
		'capital' => 'Dushanbe',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tokelau',
		'iso2'    => 'TK',
		'iso3'    => 'TKL',
		'isoNum'  => '772',
		'fips'    => 'TL',
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'East Timor',
		'iso2'    => 'TL',
		'iso3'    => 'TLS',
		'isoNum'  => '626',
		'fips'    => 'TT',
		'capital' => 'Dili',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Turkmenistan',
		'iso2'    => 'TM',
		'iso3'    => 'TKM',
		'isoNum'  => '795',
		'fips'    => 'TX',
		'capital' => 'Ashgabat',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tunisia',
		'iso2'    => 'TN',
		'iso3'    => 'TUN',
		'isoNum'  => '788',
		'fips'    => 'TS',
		'capital' => 'Tunis',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tonga',
		'iso2'    => 'TO',
		'iso3'    => 'TON',
		'isoNum'  => '776',
		'fips'    => 'TN',
		'capital' => 'Nukualofa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Turkey',
		'iso2'    => 'TR',
		'iso3'    => 'TUR',
		'isoNum'  => '792',
		'fips'    => 'TU',
		'capital' => 'Ankara',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Trinidad and Tobago',
		'iso2'    => 'TT',
		'iso3'    => 'TTO',
		'isoNum'  => '780',
		'fips'    => 'TD',
		'capital' => 'Port of Spain',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tuvalu',
		'iso2'    => 'TV',
		'iso3'    => 'TUV',
		'isoNum'  => '798',
		'fips'    => 'TV',
		'capital' => 'Funafuti',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Taiwan',
		'iso2'    => 'TW',
		'iso3'    => 'TWN',
		'isoNum'  => '158',
		'fips'    => 'TW',
		'capital' => 'Taipei',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Tanzania',
		'iso2'    => 'TZ',
		'iso3'    => 'TZA',
		'isoNum'  => '834',
		'fips'    => 'TZ',
		'capital' => 'Dodoma',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Ukraine',
		'iso2'    => 'UA',
		'iso3'    => 'UKR',
		'isoNum'  => '804',
		'fips'    => 'UP',
		'capital' => 'Kyiv',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Uganda',
		'iso2'    => 'UG',
		'iso3'    => 'UGA',
		'isoNum'  => '800',
		'fips'    => 'UG',
		'capital' => 'Kampala',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'U.S. Minor Outlying Islands',
		'iso2'    => 'UM',
		'iso3'    => 'UMI',
		'isoNum'  => '581',
		'fips'    => null,
		'capital' => '',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'United States',
		'iso2'    => 'US',
		'iso3'    => 'USA',
		'isoNum'  => '840',
		'fips'    => 'US',
		'capital' => 'Washington',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Uruguay',
		'iso2'    => 'UY',
		'iso3'    => 'URY',
		'isoNum'  => '858',
		'fips'    => 'UY',
		'capital' => 'Montevideo',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Uzbekistan',
		'iso2'    => 'UZ',
		'iso3'    => 'UZB',
		'isoNum'  => '860',
		'fips'    => 'UZ',
		'capital' => 'Tashkent',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Vatican City',
		'iso2'    => 'VA',
		'iso3'    => 'VAT',
		'isoNum'  => '336',
		'fips'    => 'VT',
		'capital' => 'Vatican',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Saint Vincent and the Grenadin',
		'iso2'    => 'VC',
		'iso3'    => 'VCT',
		'isoNum'  => '670',
		'fips'    => 'VC',
		'capital' => 'Kingstown',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Venezuela',
		'iso2'    => 'VE',
		'iso3'    => 'VEN',
		'isoNum'  => '862',
		'fips'    => 'VE',
		'capital' => 'Caracas',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'British Virgin Islands',
		'iso2'    => 'VG',
		'iso3'    => 'VGB',
		'isoNum'  => '092',
		'fips'    => 'VI',
		'capital' => 'Road Town',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'U.S. Virgin Islands',
		'iso2'    => 'VI',
		'iso3'    => 'VIR',
		'isoNum'  => '850',
		'fips'    => 'VQ',
		'capital' => 'Charlotte Amalie',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 1,
	],
	[
		'name'    => 'Vietnam',
		'iso2'    => 'VN',
		'iso3'    => 'VNM',
		'isoNum'  => '704',
		'fips'    => 'VM',
		'capital' => 'Hanoi',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Vanuatu',
		'iso2'    => 'VU',
		'iso3'    => 'VUT',
		'isoNum'  => '548',
		'fips'    => 'NH',
		'capital' => 'Port Vila',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Wallis and Futuna',
		'iso2'    => 'WF',
		'iso3'    => 'WLF',
		'isoNum'  => '876',
		'fips'    => 'WF',
		'capital' => 'Mata-Utu',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Samoa',
		'iso2'    => 'WS',
		'iso3'    => 'WSM',
		'isoNum'  => '882',
		'fips'    => 'WS',
		'capital' => 'Apia',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Kosovo',
		'iso2'    => 'XK',
		'iso3'    => 'XKX',
		'isoNum'  => null,
		'fips'    => null,
		'capital' => 'Tarawa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Yemen',
		'iso2'    => 'YE',
		'iso3'    => 'YEM',
		'isoNum'  => '887',
		'fips'    => 'YM',
		'capital' => 'Sanaa',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Mayotte',
		'iso2'    => 'YT',
		'iso3'    => 'MYT',
		'isoNum'  => '175',
		'fips'    => 'MF',
		'capital' => 'Mamoutzou',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'South Africa',
		'iso2'    => 'ZA',
		'iso3'    => 'ZAF',
		'isoNum'  => '710',
		'fips'    => 'SF',
		'capital' => 'Pretoria',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Zambia',
		'iso2'    => 'ZM',
		'iso3'    => 'ZMB',
		'isoNum'  => '894',
		'fips'    => 'ZA',
		'capital' => 'Lusaka',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
	[
		'name'    => 'Zimbabwe',
		'iso2'    => 'ZW',
		'iso3'    => 'ZWE',
		'isoNum'  => '716',
		'fips'    => 'ZI',
		'capital' => 'Harare',
		'isEU'    => 0,
		'isUK'    => 0,
		'isUS'    => 0,
	],
];