name: PHP Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  php-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1, 8.2, 8.3 ]

    name: php:${{ matrix.php }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      
      - name: Install Xdebug for PHP 8.3
        if: matrix.php == '8.3'
        run: |
          echo "Installing Xdebug..."
          pecl install xdebug
          echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
          echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini
          echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini

      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Validate Code Style
        run: composer run-script phpcs

      - name: Run tests
        run: composer run-script test
